### ISSUE TITLE
Language Word Translation Request Reverse Logic

### ISSUE THREAD

**Issue by Mastermind64222-0** [Mastermind64222-0/indigenous-namibia#25] opened 2015-10-25 19:08 UTC
When user selects a language to translate from, enter a word and select a language to translate to and user clicks on translate and that word is not available, it will be requested. For example, translate word "eumbo" from language "Oshimbaanhu" to language "English". 

Now when the word "eumbo" is not translated from language "Oshimbaanhu"  to language "English" or vice versa, and it is not available. The word will be requested. Now when a contributor adds the words and save the translation "eumbo" from language "Oshimbaanhu" to language "English" corresponding word "house". Now when a user visits the NIL home and searches for the same translation of the "eumbo" from language "Oshimbaanhu" to language "English"  the word "house" with be translated as the match in the language "English",  however if the reverse is performed, selecting language to translate from as "English" and language to translate to as "Oshimbaanhu" and enter the recently translated word "house" in the language "English" word input field and user clicks the translate button, one would expect the word "eumbo" to be returned as corresponding match to the word "house" in the language being translated to "Oshimbaanhu", however this is not the case. The word is requested instead.

**Comment by abrie** [comment] 2015-10-25 19:28
Logged as a bug.

**Comment by abrie** [comment] 2015-10-25 20:20
The issue appears to be related to Ngram's being saved without there being a string in the target field. This results in multiple translation requests being issued for the ngram, for which there is inadequet error handling the the TranslationRequest controller.

Eumbo<->house in the case Oshimbaanhu<->English was the only case in which this could be replicated. I've manually edited the production database in order to facilitate the translation in this case; but further error checks need to be implemented on the server in order to prevent this bug in the future.

**Comment by abrie** [comment] 2015-10-25 21:20
Issue resolved with deployment 0.5.3

Analysis:

Further debugging has pointed to the [seeds.csv](https://github.com/Mastermind64222-0/indigenous-namibia/commit/0906dfc9181031a34a97c1011382b1524eef0e64) as being the root cause of this issue. Several of the seed values had no translation keys, and therefore resulted in a NULL value being inserted into the Ngrams table. This null value, through the logic in the TranslationRequest controller, caused NGrams to be returned from the seek function, despite the NGram actually being invalid. The invalid NGrams where at the top of the  [seeds.csv](https://github.com/Mastermind64222-0/indigenous-namibia/commit/0906dfc9181031a34a97c1011382b1524eef0e64), and thus were assigned a group_id value of 0 and 1. Any new translations added to the system would thus be assigned a group_id of 1+1 or 0+1 (depending on the specific case), and result in a blank space being returned for the translation.

Fix:
- The seeds.csv file has been fixed so that no null values are present.
- a NOT NULL constraint has been added to the Ngram CONTENT column, to prohibit future nulls.
- The production database has been scrubbed of Ngrams with NULL values.

**Closed by abrie** 2015-10-25 21:20 UTC
Labels: bug
